# base_model: 01-ai/Yi-34B-Chat
base_model: 01-ai/Yi-6B
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: communityai/aptchat-code-math-0.5k
    type: aptchat_v2
    conversation: aptchat_v2
  - path: communityai/aptchat-v2-general-12k
    type: aptchat_v2
    conversation: aptchat_v2

dataset_prepared_path: ./dataset/01-ai/Yi-6B/aptchat-v2-general-12k_25-march-2024-08-32
push_dataset_to_hub: arpitsh018
output_dir: ./model/01-ai/Yi-6B/aptchat-v2-general-12k_25-march-2024-08-32
hf_use_auth_token: true
hub_model_id: yi-6b-aptchat-v2-general-12k_25-march-2024-08-32
hub_strategy: end
# debug: true
chat_template: aptchat_v2
    
dataset_prepared_path:
val_set_size: 0.05

sequence_len: 8192
sample_packing: false
pad_to_sequence_len: true
eval_sample_packing: false

wandb_project: neural-network
wandb_entity: arpitsh018
wandb_watch:
wandb_name: yi-6b-aptchat-v2-general-12k_25-march-2024-08-10
wandb_log_model: checkpoint

gradient_accumulation_steps: 16
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

train_on_inputs: false
group_by_length: false
bf16: true
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed: /workspace/axolotl/deepspeed_configs/zero3_bf16.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
tokens:
  - "<|im_start|>"
  - "<|im_start|>system"
  - "<|im_start|>user"
  - "<|im_start|>assistant"