base_model: 01-ai/Yi-34B
base_model_config: 01-ai/Yi-34B
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
load_in_8bit: false
load_in_4bit: false
gptq: false
strict: false
push_dataset_to_hub: true
hf_use_auth_token: true
datasets:
  - path: communityai/aptchatv1-template-micro-dataset-llm-v2-714k
    type: aptchat
dataset_prepared_path:
val_set_size: 0.002
noisy_embedding_alpha: 5.0

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true
max_packed_sequence_len:

# adapter:
# lora_model_dir:
# lora_r: 64
# lora_alpha: 32
# lora_dropout: 0.0
# lora_target_modules:
# lora_target_linear: true
# lora_fan_in_fan_out:

wandb_project: neural-network
wandb_entity: neural-network-018
wandb_watch:
wandb_run_id:
wandb_log_model:
output_dir: ./01-ai-yi-34b

gradient_checkpointing: true
gradient_accumulation_steps: 4
# batch_size: 8
micro_batch_size: 8
eval_batch_size: 8
num_epochs: 3
optimizer: adamw_bnb_8bit
torchdistx_path:
lr_scheduler: cosine
learning_rate: 0.00002
train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true

early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: true
flash_attention: true
gptq_groupsize:
gptq_model_v1:
warmup_steps: 100
eval_steps: 500
save_steps: 2
debug:
deepspeed: deepspeed/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|endoftext|>"
  bos_token: "<|startoftext|>"
  eos_token: "<|endoftext|>"
  unk_token: "<unk>"
